apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-strv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-strv
    app.kubernetes.io/part-of: tkrw-pr712-0075-0021-app
  name: devfile-sample-strv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-strv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-strv
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0021-tenant/tkrw-pr712-0075-0021-app/devfile-sample-strv@sha256:84773a82e34cecc3a5877c274a03e082a55d21a9417bbb0aa07e0902a3a7b33f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
